# What you can put in this file: https://docs.papermc.io/paper/dev/plugin-yml
name: Teleios
version: 1.3WIP
main: de.daniel_d45.teleios.core.main.Teleios
description: "Adds miscellaneous features which can be switched on and off using the /manageteleios command."
api-version: "1.20"
author: Daniel_D45
website: https://github.com/DanielD45/Teleios/

commands:

  # AdminFeatures commands
  chatclear:
    aliases: [ cc, CC ]
    permission: teleios.adminfeatures.chatclear
    description: Clears the chat.
    usage: /chatclear

  damage:
    aliases: [ d, D ]
    permission: teleios.adminfeatures.damage
    description: Damages you or another player.
    usage: /damage <Amount>, /damage <Player> <Amount>

  gma:
    aliases: [ GMA ]
    permission: teleios.adminfeatures.gma
    description: Sets you or another player in adventure mode.
    usage: /gma, /gma <Player>

  gmc:
    aliases: [ GMC ]
    permission: teleios.adminfeatures.gmc
    description: Sets you or another player in creative mode.
    usage: /gmc, /gmc <Player>

  gms:
    aliases: [ GMS ]
    permission: teleios.adminfeatures.gms
    description: Sets you or another player in survival mode.
    usage: /gms, /gms <Player>

  gmsp:
    aliases: [ GMSP ]
    permission: teleios.adminfeatures.gmsp
    description: Sets you or another player in spectator mode.
    usage: /gmsp, /gmsp <Player>

  heal:
    aliases: [ h, H ]
    permission: teleios.adminfeatures.heal
    description: Heals you or another player.
    usage: /heal, /heal <Amount>, /heal <Player>, /heal <Player> <Amount>

  inventories:
    aliases: [ invs, INVS ]
    permission: teleios.adminfeatures.inventories
    description: Let's you create, open and manage custom inventories with an amount of rows lower than 7.
    usage: /invs (list|clear), /invs (open|remove), /invs create <Name>, /invs create <Name> <Rows>

  joinmessage:
    aliases: [ jm, JM ]
    permission: teleios.adminfeatures.joinmessageRead
    description: Lets you enable or disable the custom join message.
    usage: /joinmessage enable|true|disable|false

  makepersonallootchest:
    aliases: [ plc, PLC, makeplc, MAKEPLC ]
    permission: teleios.adminfeatures.makepersonallootchest
    description: Lets you change a chest into a personal loot chest.
    usage: /makepersonallootchest

  mute:
    aliases: [ m, M ]
    permission: teleios.adminfeatures.mute
    description: Lets you mute players.
    usage: /mute <Player>

  openinventory:
    aliases: [ oi, OI ]
    permission: teleios.adminfeatures.openinventory
    description: Opens the specified player's inventory.
    usage: /openinventory <Player>

  oplist:
    aliases: [ opl, OPL ]
    permission: teleios.adminfeatures.oplist
    description: Lets you store ops on a list. These people can op themselves anytime.
    usage: /oplist , /oplist add <Name>

  tphere:
    aliases: [ tph, TPH ]
    permission: teleios.adminfeatures.tphere
    description: Teleports another player to you.
    usage: /tphere <Player>

  unmute:
    aliases: [ um, UM ]
    permission: teleios.adminfeatures.unmute
    description: Lets you unmute players.
    usage: /unmute <Player>

  warppoint:
    aliases: [ wp, WP ]
    permission: teleios.adminfeatures.warppoint
    description: Lets you modify warppoints.
    usage: /warppoint (list|clear), /warppoint (add|remove|override) <Name>

  # BetterGameplay commands
  configureteleporter:
    aliases: [ ctp, CTP ]
    permission: teleios.bettergameplay.configureteleporter
    description: Lets you change the name of a teleporter you hold in your hand.
    usage: /configureteleporter <Name>

  enderchest:
    aliases: [ ec, EC ]
    permission: teleios.bettergameplay.enderchest
    description: Opens your enderchest.
    usage: /enderchest

  setblocksperpearl:
    aliases: [ sbpp, SBPP ]
    permission: teleios.bettergameplay.setblocksperpearlRead
    description: Lets you change the amount of blocks you can travel per ender pearl when warping to a teleporter.
    usage: /setblocksperpearl, /setblocksperpearl <Amount>

  warp:
    aliases: [ w, W ]
    permission: teleios.bettergameplay.warp
    description: Lists available teleporters and warppoints and warps you there.
    usage: /warp , /warp (list|<Teleporter>|<Warppoint>)

  warppouch:
    aliases: [ wpp, WPP ]
    permission: teleios.bettergameplay.warppouch
    description: Lets you see and deposit ender pearls in your warppouch.
    usage: /warppouch, /warppouch view|show, /warppouch deposit|put, /warppouch deposit|put <Amount>

  # Core commands
  manageteleios:
    aliases: [ mtl, MTL ]
    permission: teleios.adminfeatures.manageteleios
    description: Let's you enable and disable the plugin segments and functionality.
    usage: /manageteleios

  # PassiveSkills commands
  skills:
    aliases: [ s, S ]
    permission: teleios.passiveskills.skills
    description: Shows your skills in an inventory.
    usage: /skills


permissions:

  # AdminFeatures permissions
  teleios.adminfeatures.chatclear:
    description: Allows use of the chatclear command.
    default: op

  teleios.adminfeatures.damage:
    description: Allows use of the damage command.
    default: op

  teleios.adminfeatures.gma:
    description: Allows use of the gma command.
    default: op

  teleios.adminfeatures.gmc:
    description: Allows use of the gmc command.
    default: op

  teleios.adminfeatures.gms:
    description: Allows use of the gms command.
    default: op

  teleios.adminfeatures.gmsp:
    description: Allows use of the gmsp command.
    default: op

  teleios.adminfeatures.heal:
    description: Allows use of the heal command.
    default: op

  teleios.adminfeatures.inventories:
    description: Allows use of the inventories command.
    default: op

  teleios.adminfeatures.joinmessageRead:
    description: Allows querying the JoinMessage argument using /joinmessage.
    default: true

  teleios.adminfeatures.joinmessage:
    description: Allows use of the joinmessage command.
    default: op

  teleios.adminfeatures.makepersonallootchest:
    description: Allows use of the makepersonallootchest command.
    default: op

  teleios.adminfeatures.mute:
    description: Allows use of the mute command.
    default: op

  teleios.adminfeatures.openinventory:
    description: Allows use of the openinventory command.
    default: op

  teleios.adminfeatures.oplist:
    description: Allows use of the oplist command.
    default: true

  teleios.adminfeatures.oplistAdd:
    description: Allows adding people to the OP list using the oplist command.
    default: op

  teleios.adminfeatures.tphere:
    description: Allows use of the tphere command.
    default: op

  teleios.adminfeatures.unmute:
    description: Allows use of the unmute command.
    default: op

  # BetterGameplay permissions
  teleios.bettergameplay.configureteleporter:
    description: Allows use of the configureteleporter command.
    default: true

  teleios.bettergameplay.enderchest:
    description: Allows use of the enderchest command.
    default: true

  teleios.bettergameplay.setblocksperpearlRead:
    description: Allows querying the BlocksPerPearl argument using /setblocksperpearl.
    default: true

  teleios.bettergameplay.setblocksperpearl:
    description: Allows use of the setblocksperpearl command.
    default: op

  teleios.bettergameplay.warp:
    description: Allows use of the warp command.
    default: true

  teleios.bettergameplay.warppoint:
    description: Allows use of the warppoint command.
    default: op

  teleios.bettergameplay.warppouch:
    description: Allows use of the warppouch command.
    default: true

  # Core permissions
  teleios.core.manageteleios:
    description: Allows use of the manageteleios command.
    default: op

  # PassiveSkills permissions
  teleios.passiveskills.skills:
    description: Allows use of the skills command.
    default: true
